name: IdealChat
author: roblikescake
main: net.simplicite_mc.roblikescake.idealchat.IdealChat
description: It does stuff
version: ${project.version}-b${BUILD_NUMBER}

commands:
    channel:
        description: Usage /channel